#!/bin/bash
# Safe scanning iteration loops
for file in ~/OS-SE-p20240033/final-exam/partC_scripting/data/*; do
    if [ -f "$file" ] && [ -r "$file" ]; then
        echo "[READABLE]: $file -> $(cat "$file")"
    fi
done
